name: yomu
description: Pure Dart QR code and barcode reader library with zero dependencies.
version: 1.0.0
repository: https://github.com/koji-1009/yomu
issue_tracker: https://github.com/koji-1009/yomu/issues

topics:
  - qr-code
  - barcode
  - scanner
  - reader

environment:
  sdk: ^3.9.0

dev_dependencies:
  coverage: ^1.15.0
  image: ^4.7.0
  lints: ^6.0.0
  pool: ^1.5.0
  qr: ^3.0.2
  test: ^1.25.6
  dapper: ^1.4.0
